export const POST_VIDEOGAME = "POST_VIDEOGAME";
export const GET_VIDEOGAMES = "GET_VIDEOGAMES";
export const REGISTER_USER = "REGISTER_USER";
export const REGISTER_USER_SUCCESS = "REGISTER_USER_SUCCESS";
export const REGISTER_USER_ERROR = "REGISTER_USER_ERROR";
export const ORDERS = "ORDERS";
